name: 🚀 Deploy a InfinityFree por FTP

on:
  push:
    branches:
      - main # Ajusta según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: 💾 Obtener directorio de caché de Composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 💾 Configurar caché de Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 🛠️ Instalar PHP y Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: 📦 Instalar dependencias en ReservationSystem
        working-directory: ./ReservationSystem
        run: composer install --no-dev --optimize-autoloader

      - name: 📤 Subir carpeta ReservationSystem por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.ftp_password }}
          local-dir: ReservationSystem/
          server-dir: htdocs/
